#!/bin/sh
# live-build auto configuratie voor ZolumaOS
# Draait automatisch bij: lb config

lb config noauto \
    --architecture amd64 \
    --distribution noble \
    --archive-areas "main restricted universe multiverse" \
    --debian-installer none \
    --bootappend-live "boot=live components locales=nl_NL.UTF-8 keyboard-layouts=nl timezone=Europe/Amsterdam" \
    --iso-volume "ZolumaOS" \
    --iso-application "ZolumaOS" \
    "${@}"
